openapi: 3.0.2
info:
  version: 1.0.0
  title: Newcomer training API
servers:
  - url: http://localhost:4000
    description: development
paths:
  "/comments":
    get:
      summary: コメント一覧の取得
      responses:
        "200":
          $ref: "#/components/responses/Comments"
    post:
      summary: コメントの作成
      requestBody:
        $ref: "#/components/requestBodies/Comment"
      responses:
        "200":
          $ref: "#/components/responses/Comment"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
components:
  schemas:
    CommentProperties:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 山田太郎
        content:
          type: string
          example: こんにちは！
        created_at:
          type: string
          format: data-time
          example: "2020-04-01T00:00:00Z"
      required:
        - id
        - name
        - content
        - created_at
    CommentParameters:
      type: object
      properties:
        name:
          type: string
          example: 山田太郎
        content:
          type: string
          example: こんにちは！
      required:
        - name
        - content
    CommentRequest:
      type: object
      properties:
        comment:
          $ref: "#/components/schemas/CommentParameters"
      required:
        - comment
    ErrorProperties:
      type: object
      properties:
        title:
          type: string
          example: Something went wrong
        detail:
          type: string
          example: Please try again later.
      required:
        - title
        - detail
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/ErrorProperties"
  requestBodies:
    Comment:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CommentRequest"
  responses:
    Comment:
      description: コメント
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CommentProperties"
    Comments:
      description: コメントの配列
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/CommentProperties"
    UnprocessableEntity:
      description: 無効なパラメータ
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Errors"
